; [mongodb]
; mongodb-dev.cineniti.in

; [catalogue]
; catalogue-dev.cineniti.in

; [redis]
; redis-dev.cineniti.in

; [user]
; user-dev.cineniti.in

; [cart]
; cart-dev.cineniti.in

; [mysql]
; mysql-dev.cineniti.in

; [shipping]
; shipping-dev.cineniti.in

; [rabbitmq]
; rabbitmq-dev.cineniti.in

; [payment]
; payment-dev.cineniti.in

; [frontend]
; frontend-dev.cineniti.in

[locals]
localhost












